"""Add email password authentication support

Revision ID: 4c79a656f305
Revises: 
Create Date: 2025-11-21 23:25:28.153514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c79a656f305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###